# Generated by Django 5.1.3 on 2024-11-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='еда')),
                ('ingredients', models.TextField(verbose_name='ингредиенты')),
                ('instructions', models.TextField(verbose_name='инструкция по готовке')),
                ('prep_time', models.IntegerField(verbose_name='время готовки')),
                ('is_vegetarian', models.BooleanField(default=False, verbose_name='еда вегетареанское')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='день дегустации')),
            ],
            options={
                'verbose_name_plural': 'вкусная кухня😋',
            },
        ),
    ]
